### ISSUE TITLE
Unable to run the clc step 1 model with the instructions provided

### ISSUE THREAD

**Issue by anupamajha1** [DOE-NCI-MOSSAIC/FrESCO#32]
Hi, 

I tried running the following command from your README. 

`python train_model.py -m ie -args ../configs/clc_step1.yml`

after installing the fresco model from the source code

```

git clone https://github.com/DOE-NCI-MOSSAIC/FrESCO.git
conda env create -n fresco python=3.9
conda activate fresco
pip install .
```

and decompressing the datasets (using tar -xf command)

 but ran into the following error. 

```
Process started
Wed Aug  2 17:09:06 2023 

Running information extraction task
Validating kwargs in model_args.yml file

Received:  ['add_noise', 'add_noise_flag', 'batch_per_gpu', 'data_path', 'doc_max_len', 'fold_number', 'multilabel', 'random_seed', 'reproducible', 'subset_proportion', 'tasks']
Expected:  ['add_noise', 'add_noise_flag', 'batch_per_gpu', 'data_path', 'doc_max_len', 'fold_number', 'multilabel', 'mutual_info_filter', 'mutual_info_threshold', 'random_seed', 'reproducible', 'subset_proportion', 'tasks']
Traceback (most recent call last):
  File "/net/noble/vol3/user/anupamaj/proj/2023_openjournal_review/FrESCO/scripts/train_model.py", line 64, in <module>
    main()
  File "/net/noble/vol3/user/anupamaj/proj/2023_openjournal_review/FrESCO/scripts/train_model.py", line 51, in main
    run_ie.run_ie(args)
  File "/net/noble/vol1/home/anupamaj/miniconda3/fresco/lib/python3.9/site-packages/fresco/run_ie.py", line 141, in run_ie
    valid_params.check_data_train_args()
  File "/net/noble/vol1/home/anupamaj/miniconda3/fresco/lib/python3.9/site-packages/fresco/validate/validate_params.py", line 175, in check_data_train_args
    raise exceptions.ParamError((f"model args {kwrd} does not have " +
fresco.validate.exceptions.ParamError: model args data_kwargs does not have the expected variables
```

**Comment by aspannaus** [comment]
Hi @anupamajha1,

Thanks for looking at this. I think it is related to a comment from the other JOSS reviewer, and we edited the config file, removing unnecessary args. Which branch are you on, and when did you pull it? I pulled a fresh version of `main` and step 1 of clc runs as expected. If you can provide these details, we should be able to get things straightened out in short order.

Thanks

**Comment by anupamajha1** [comment]
Hi @aspannaus, I am on the main branch and I ran this on code I pulled today morning (Aug 2, 2023). However, after your comment, I pulled your latest changes from the main branch (Aug 2, 2023, 7:20 PM PST) and reinstalled everything and ran the command again but I still get the same error as before (see below). 

```
python train_model.py -m ie -args ../configs/clc_step1.yml

Process started
Wed Aug  2 19:21:52 2023 

Running information extraction task
Validating kwargs in model_args.yml file

Received:  ['add_noise', 'add_noise_flag', 'batch_per_gpu', 'data_path', 'doc_max_len', 'fold_number', 'multilabel', 'random_seed', 'reproducible', 'subset_proportion', 'tasks']
Expected:  ['add_noise', 'add_noise_flag', 'batch_per_gpu', 'data_path', 'doc_max_len', 'fold_number', 'multilabel', 'mutual_info_filter', 'mutual_info_threshold', 'random_seed', 'reproducible', 'subset_proportion', 'tasks']
Traceback (most recent call last):
  File "/net/noble/vol3/user/anupamaj/proj/2023_openjournal_review/FrESCO/scripts/train_model.py", line 64, in <module>
    main()
  File "/net/noble/vol3/user/anupamaj/proj/2023_openjournal_review/FrESCO/scripts/train_model.py", line 51, in main
    run_ie.run_ie(args)
  File "/net/noble/vol1/home/anupamaj/miniconda3/fresco/lib/python3.9/site-packages/fresco/run_ie.py", line 141, in run_ie
    valid_params.check_data_train_args()
  File "/net/noble/vol1/home/anupamaj/miniconda3/fresco/lib/python3.9/site-packages/fresco/validate/validate_params.py", line 175, in check_data_train_args
    raise exceptions.ParamError((f"model args {kwrd} does not have " +
fresco.validate.exceptions.ParamError: model args data_kwargs does not have the expected variables
```

**Comment by anupamajha1** [comment]
I deleted everything and reinstalled the repository from scratch again at 7:46 PM PST, Aug 2, 2023, and I still get the same error. I will wait for the resolution of this issue for my review.

**Comment by aspannaus** [comment]
Hi @anupamajha1,

I've figured out the issue; the code on pypi is slightly older than that in the repo. If you run `pip install -e .` it runs as expected. The person on the team who set up the pypi account is out right now, and we'll update that as well once they're back in the office. 

Thanks

**Comment by anupamajha1** [comment]
Hi @aspannaus, Thanks for addressing the issue, I can run train_model.py if I pip install with -e option. Please don't forget to update the pypi version.
